classDiagram
    class PresentationLayer {
        <<Layer>>
        API
        Services
    }

    class BusinessLogicLayer {
        <<Layer>>
        Facade
        User
        Place
        Review
        Amenity
    }

    class PersistenceLayer {
        <<Layer>>
        Repository
        Database
    }

    PresentationLayer --> BusinessLogicLayer : Facade Pattern
    BusinessLogicLayer --> PersistenceLayer : CRUD Operations
